### ISSUE TITLE
File path treatment fails on Windows

### ISSUE THREAD

**Issue by ahoho** [ICIJ/extract#1]
I've discovered two problems relating to file path resolution (which I'd be happy to try to fix with some guidance).

- For some reason, using `--file-output-directory` with `spew` only works with a the first folder specified in a path. So specifying the output as `C:/folder` actually only sends something to `C:/`.
- Inputting a file path with a colon (like `C:/`) causes an `InvalidPathException`, (altering the path so that it uses a server address, e.g., `//myfs/`, causes problems as well)

**Comment by mattcg** [comment]
Hi @ahoho, thank you for reporting this. What terminal environment are you using on Windows?

**Comment by ahoho** [comment]
I believe I was running this using the standard Windows command prompt. Should I be working in cygwin?

**Comment by mattcg** [comment]
I've tested on Windows and it works fine. I think you're specifying paths in the wrong format. It should be `C:\` NOT `C:/`. Windows uses a different path separator.
