### ISSUE TITLE
Build error - log attached

### ISSUE THREAD

**Issue by gardsted** [ICIJ/extract#2]
I tried to build but got stuck in a test - not that severe, I think - but I cant find any built application, so it is 'that' severe.

    log (mvn install -e -X > log 2>&1) attached.

[log.txt](https://github.com/ICIJ/extract/files/386477/log.txt)

**Comment by mattcg** [comment]
Hi Jorgen, thanks for filing this. Do you have Tesseract installed? If not, that's probably why the tests are failing.

**Comment by gardsted** [comment]
wow - thanks - I will try again.

**Comment by gardsted** [comment]
Yes - that did the trick: 

    apt-get install tesseract-ocr

Thank You very much. Can't wait to play with it.

**Comment by mattcg** [comment]
Excellent! Don't forget to install the additional language libraries for Tesseract if you need them.

**Comment by gardsted** [comment]
As I am a rare java user, I will post my findings  - some of them may be obvious to most, but still help others like me.
Just tell me to stop or try to correct/contrib to docu, if You would rather have me do that.
-
1) Documentation speaks of an 'extract' executable. but I only find 'extract-capsule.x':

    myname@extract:~/extract$ find target -type f -executable -ls | grep extract
      5771654  56264 -rwxrwxr-x   1 myname      myname      57610454 jul 29 10:49 target/extract-capsule.x

2) Program will not run without JAVA_OPTS

    myname@extract:~/extract$ unset JAVA_OPTS
    myname@extract:~/extract$ ./target/extract-capsule.x
    CAPSULE EXCEPTION: Exception while getting attribute JVM-Args while processing environment variable JAVA_OPTS: null (for stack trace, run with -Dcapsule.log=verbose)

3) setting minimum JAVA_OPTS

    myname@extract:~/extract$ export JAVA_OPTS='\"-Xms1024m -Xmx10240m\"'
    myname@extract:~/extract$ ./target/extract-capsule.x
    Error: Could not find or load main class ."-Xms1024m

Look how far I got without help :-)

**Comment by mattcg** [comment]
Thanks to the issue you've raised here I've moved a lot of this info to the wiki. Please check it out and let me know if you have any comments!
