### ISSUE TITLE
no -d option for spew as seen in docu

### ISSUE THREAD

**Issue by gardsted** [ICIJ/extract#3]
docu says

    extract spew -d /path/to/files -r redis -o file --file-output-directory /path/to/text

but:
 
    export JAVA_OPTS='-Xms1024m -Xmx10240m'
    extract spew -d /path/to/files -r redis -o file --file-output-directory /path/to/text

gives:

    myname@extract:~/extract$ ./target/extract-capsule.x  spew -d /tmp/input -r redis -o file --file-output-directory /tmp/output
    Jul 29, 2016 11:52:45 AM org.icij.extract.cli.Main main
    SEVERE: Failed to parse command line arguments: Unrecognized option: -d

I guess I have to look at the working directory and pattern options instead.

**Comment by gardsted** [comment]
Got it:

    ./target/extract-capsule.x  spew  -o stdout  /tmp/input

Thank You very much - I will play around a bit.

**Comment by mattcg** [comment]
Thanks for pointing this out.
