### ISSUE TITLE
spew spews exceptions for subdirectories

### ISSUE THREAD

**Issue by gardsted** [ICIJ/extract#4]
Maybe that is intended, but.:

     ./target/extract-capsule.x  spew  -o stdout  /usr/share >/dev/null

Will give lots of errors like.:

    Jul 29, 2016 12:13:33 PM org.icij.extract.core.Consumer extract
    SEVERE: The document stream could not be read: /usr/share/doc/console-setup.
    org.apache.tika.io.TaggedIOException: Is a directory

Furthermore - i find the period after the SEVERE line annoying - it is hard to know if it is part of the name reported or not.

**Comment by mattcg** [comment]
Thanks for reporting this. The fix is to ignore symbolic links when you don't specify the `--follow-symlinks` option.
