### ISSUE TITLE
Build failure (org.icij.kaxxa:) .. could not be resolved

### ISSUE THREAD

**Issue by PaulHughes99** [ICIJ/extract#9]
Hi - not succeeding in building, after following Wiki build instructions:
After 'mvn install' on command line...
error on Mac:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:00 min
[INFO] Finished at: 2017-08-13T12:55:02+02:00
[INFO] Final Memory: 21M/137M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project extract: Could not resolve dependencies for project org.icij.extract:extract:jar:2.0.0: The following artifacts could not be resolved: org.icij.kaxxa:kaxxa-concurrent:jar:1.0-SNAPSHOT, org.icij.kaxxa:kaxxa-events:jar:1.0-SNAPSHOT, org.icij.kaxxa:kaxxa-io:jar:1.0-SNAPSHOT, org.icij.kaxxa:kaxxa-sql:jar:1.0-SNAPSHOT: Could not find artifact org.icij.kaxxa:kaxxa-concurrent:jar:1.0-SNAPSHOT in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

REPRODUCING SAME ERROR (on AWS Ubuntu 15.6.0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:00 min
[INFO] Finished at: 2017-08-13T12:55:02+02:00
[INFO] Final Memory: 21M/137M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project extract: Could not resolve dependencies for project org.icij.extract:extract:jar:2.0.0: The following artifacts could not be resolved: org.icij.kaxxa:kaxxa-concurrent:jar:1.0-SNAPSHOT, org.icij.kaxxa:kaxxa-events:jar:1.0-SNAPSHOT, org.icij.kaxxa:kaxxa-io:jar:1.0-SNAPSHOT, org.icij.kaxxa:kaxxa-sql:jar:1.0-SNAPSHOT: Could not find artifact org.icij.kaxxa:kaxxa-concurrent:jar:1.0-SNAPSHOT in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by mattcg** [comment]
Hi Paul, will you try with the latest commit please?

**Comment by PaulHughes99** [comment]
Thanks - that sorts it.
